name: Pack and Attach Addon to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Create Addon Structure
        run: |
          mkdir WeintCodex

          rsync -a \
            --exclude=".git" \
            --exclude=".github" \
            --exclude=".gitignore" \
            --exclude="README.md" \
            --exclude="LICENSE" \
            --exclude="WeintCodex" \
            ./ WeintCodex/

      - name: Create ZIP
        run: |
          zip -r "WeintCodex-${VERSION}.zip" WeintCodex

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: WeintCodex-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
